### ISSUE TITLE
Incorrect dependency names on ROS packages

### ISSUE THREAD

**Issue by amc-nu** [fzi-forschungszentrum-informatik/Lanelet2#37] opened 2019-06-18 08:11 UTC
Unresolvable dependencies by `rosdep` due to incorrect naming on:
1. `libgeographic-dev` should read instead [`geographiclib`](https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L959) 
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/034bdecc29e0f4978321cd895f00f9ec78ab5237/lanelet2_projection/package.xml#L16
1. `pugixml` should *not* be listed on
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/034bdecc29e0f4978321cd895f00f9ec78ab5237/lanelet2_io/package.xml#L17
and instead be installed with apt just like the in the provided Dockerfile.
1. `boost-python` should *not* be listen on
https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/034bdecc29e0f4978321cd895f00f9ec78ab5237/lanelet2_python/package.xml#L20

**Comment by m-naumann** [comment] 2019-06-18 18:35
Duplicate of https://github.com/fzi-forschungszentrum-informatik/Lanelet2/pull/33

**Comment by poggenhans** [comment] 2019-06-24 22:02
Fixed with 7579848a554b9e3e9d30182e5994b3d530de561a. This should work after ros/rosdistro#21570 has been merged.

**Closed by poggenhans** 2019-06-24 22:02 UTC
