### ISSUE TITLE
lanelet_rviz_plugin_ros

### ISSUE THREAD

**Issue by xiaozhi12345678** [fzi-forschungszentrum-informatik/Lanelet2#15] opened 2019-03-31 03:35 UTC
Hello,I have an issue with lanelet_rviz_plugin_ros,and I am looking forward for your reply.

  I catkin_make succeeded,but when I input command "roslaunch lanelet_rviz_plugin_ros sample_lanelet_viz.launch",the error occurs,"PluginlibFactory: The plugin for class 'lanelet_rviz_plugin_ros::LaneletMapPlugin' failed to load. Error: Failed to load library /.../catkin_ws/devel/lib//liblanelet_rviz_plugin_ros.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /.../catkin_ws/devel/lib//liblanelet_rviz_plugin_ros.so: undefined symbol: _ZTVN22lanelet2_interface_ros20Lanelet2InterfaceRosE)".

  Could you please tell me how to solve it, thank you!

**Comment by poggenhans** [comment] 2019-03-31 15:42
Sorry, this isn't the right place to file issues about `lanelet_rviz_plugin_ros`. Closing this as a duplicate of coincar-sim/lanelet_rviz_plugin_ros#2.

**Closed by poggenhans** 2019-03-31 15:42 UTC
